version: '3'

services: 
  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfspreview-ipfs
    ports: 
      - '127.0.0.1:4001:4001'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:5001:5001'
    volumes:
      - ./ipfs_stage:/export
